version: "3.8"

services:
  rag-app:
    build:
      context: .
      dockerfile: dockerfile.rag
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./vectorstore:/app/vectorstore
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - RETRIEVER_TYPE=${RETRIEVER_TYPE}
    restart: unless-stopped
